In [9]:
import os 
from pathlib import Path 
import pandas as pd 
import numpy as np

In [11]:
os.chdir("student-dropout-enrolled-graduate-rate-prediction")

In [12]:
print(os.getcwd())

e:\project_archive\student-dropout-enrolled-graduate-rate-prediction

In [13]:
# Load data

data_path = Path("data/processed")
if not data_path.exists():
    raise FileNotFoundError

X_train = pd.read_csv(data_path / "x_train.csv", sep=';')
y_train = np.load(data_path / "y_train.npy")

X_test = pd.read_csv(data_path / "x_test.csv", sep=';')
y_test = np.load(data_path / "y_test.npy")

In [14]:
X_train.head()

,Marital status,Application mode,Application order,Course,Previous qualification,Previous qualification (grade),Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Inflation rate
0,4,7,1,9147,3,130.0,19,1,5,5,...,0,1,0,0,35,5,5,0,0.000000,0.6
1,1,39,1,9085,1,130.0,37,37,6,6,...,0,1,0,1,25,6,13,3,11.666667,0.6
2,1,1,6,9070,6,119.0,1,1,9,9,...,0,1,1,0,22,6,6,6,14.166667,1.4
3,2,39,1,9238,19,133.1,37,37,9,4,...,0,1,1,0,42,6,0,0,0.000000,2.8
4,1,1,3,9500,1,142.0,37,38,9,9,...,0,1,0,1,22,7,7,6,13.900000,2.6

In [15]:
y_train

array([0, 1, 2, ..., 2, 2, 0], shape=(3539,))

In [16]:
X_test.head()

,Marital status,Application mode,Application order,Course,Previous qualification,Previous qualification (grade),Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Inflation rate
0,4,39,1,9130,1,133.1,3,1,5,5,...,0,1,0,1,30,6,7,0,0.000000,0.6
1,1,17,1,9238,1,125.0,4,3,1,1,...,0,1,0,0,18,6,9,5,11.571429,0.3
2,1,17,1,9853,1,133.0,38,38,9,9,...,1,1,0,1,18,7,7,7,12.714286,0.3
3,1,17,2,9670,1,110.0,1,1,4,10,...,0,1,1,0,19,6,8,6,13.857143,2.8
4,1,39,1,9500,1,130.0,37,19,9,8,...,0,1,0,0,27,7,14,0,0.000000,0.6

In [17]:
config = {
    "xgboost": {
        "n_estimators": (200, 1000),
        "learning_rate": (0.01, 0.3),
        "max_depth": (3, 10),
        "min_child_weight": (1, 10),
        "subsample": (0.6, 1.0),
        "colsample_bytree": (0.6, 1.0),
        "gamma": (0.0, 5.0),
        "reg_alpha": (1e-5, 10.0),
        "reg_lambda": (1e-5, 10.0),
    }
}

In [18]:
from xgboost import XGBClassifier


def suggest_params(trial, config):

    cfg = config["xgboost"]

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators",
            cfg["n_estimators"][0],
            cfg["n_estimators"][1],
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            cfg["learning_rate"][0],
            cfg["learning_rate"][1],
            log=True,
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            cfg["max_depth"][0],
            cfg["max_depth"][1],
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            cfg["min_child_weight"][0],
            cfg["min_child_weight"][1],
        ),

        "subsample": trial.suggest_float(
            "subsample",
            cfg["subsample"][0],
            cfg["subsample"][1],
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            cfg["colsample_bytree"][0],
            cfg["colsample_bytree"][1],
        ),

        "gamma": trial.suggest_float(
            "gamma",
            cfg["gamma"][0],
            cfg["gamma"][1],
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            cfg["reg_alpha"][0],
            cfg["reg_alpha"][1],
            log=True,
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            cfg["reg_lambda"][0],
            cfg["reg_lambda"][1],
            log=True,
        ),
    }

    return params

In [19]:
import wandb
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score


def objective(trial, X, y, config):

    params = suggest_params(
        trial=trial,
        config=config,
    )

    model = XGBClassifier(
        **params,
        objective="multi:softprob",
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1,
    )

    cv = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=42,
    )

    scores = cross_val_score(
        estimator=model,
        X=X,
        y=y,
        cv=cv,
        scoring="f1_macro",
        n_jobs=-1,
        error_score="raise",
    )

    mean_score = scores.mean()
    std_score = scores.std()

    trial.set_user_attr("cv_std", std_score)

    wandb.log({
        "trial": trial.number,
        "cv_f1_macro": mean_score,
        "cv_f1_macro_std": std_score,
    })

    return mean_score

In [20]:
import pandas as pd
import optuna
import wandb

from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)

with wandb.init(
    project="student-drop-enroll-grad-preds",
    name="XGBoost-Optuna-v1",
    group="XGBoost",
    tags=["Optuna", "Hyperparameter-Tuning"],
    config={
        "model": "XGBoost",
        "cv": "StratifiedKFold",
        "metric": "f1_macro",
        "n_trials": 40,
        "random_state": 42,
    },
):

    study = optuna.create_study(
        direction="maximize",
        study_name="xgboost_tuning",
    )

    study.optimize(
        lambda trial: objective(
            trial,
            X_train,
            y_train,
            config,
        ),
        n_trials=80,
        show_progress_bar=True,
    )

    best_params = study.best_params

    final_model = XGBClassifier(
        **best_params,
        objective="multi:softprob",
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1,
    )

    final_model.fit(X_train, y_train)

    predictions = final_model.predict(X_test)

    metrics = {
        "test_accuracy": accuracy_score(y_test, predictions),
        "test_balanced_accuracy": balanced_accuracy_score(y_test, predictions),
        "test_precision_macro": precision_score(
            y_test,
            predictions,
            average="macro",
            zero_division=0,
        ),
        "test_recall_macro": recall_score(
            y_test,
            predictions,
            average="macro",
            zero_division=0,
        ),
        "test_f1_macro": f1_score(
            y_test,
            predictions,
            average="macro",
        ),
        "test_f1_weighted": f1_score(
            y_test,
            predictions,
            average="weighted",
        ),
    }

    wandb.log(metrics)

    wandb.summary["best_cv_f1_macro"] = study.best_value
    wandb.summary["best_trial"] = study.best_trial.number
    wandb.summary["best_params"] = best_params

    for key, value in metrics.items():
        wandb.summary[key] = value

    results = pd.DataFrame(
        {
            "Actual": y_test,
            "Prediction": predictions,
        }
    )

    wandb.log(
        {
            "Predictions": wandb.Table(dataframe=results)
        }
    )

e:\project_archive\student-dropout-enrolled-graduate-rate-prediction\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
wandb: Currently logged in as: h41497254 (h41497254-none) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

[I 2026-08-12 18:36:42,731] A new study created in memory with name: xgboost_tuning
Best trial: 0. Best value: 0.661477:   1%|▏         | 1/80 [00:08<11:04,  8.42s/it]

[I 2026-08-12 18:36:51,147] Trial 0 finished with value: 0.6614771853629376 and parameters: {'n_estimators': 607, 'learning_rate': 0.2155750686102058, 'max_depth': 8, 'min_child_weight': 6, 'subsample': 0.7066472292898056, 'colsample_bytree': 0.6205799154220394, 'gamma': 1.7506614509811484, 'reg_alpha': 0.005453482479592284, 'reg_lambda': 0.004344633907546533}. Best is trial 0 with value: 0.6614771853629376.

Best trial: 1. Best value: 0.665966:   2%|▎         | 2/80 [00:13<08:28,  6.52s/it]

[I 2026-08-12 18:36:56,340] Trial 1 finished with value: 0.6659658720592361 and parameters: {'n_estimators': 588, 'learning_rate': 0.08069709529400368, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.8255074560919125, 'colsample_bytree': 0.6992465910276433, 'gamma': 1.4704811574892513, 'reg_alpha': 0.0003908806176990394, 'reg_lambda': 0.0008373707110025798}. Best is trial 1 with value: 0.6659658720592361.

Best trial: 1. Best value: 0.665966:   4%|▍         | 3/80 [00:15<05:27,  4.25s/it]

[I 2026-08-12 18:36:57,890] Trial 2 finished with value: 0.6224211547533705 and parameters: {'n_estimators': 652, 'learning_rate': 0.07010383997039331, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9173924777880502, 'colsample_bytree': 0.7779898109806738, 'gamma': 3.3431289975227068, 'reg_alpha': 4.888160878048282, 'reg_lambda': 0.1229153837467509}. Best is trial 1 with value: 0.6659658720592361.

Best trial: 1. Best value: 0.665966:   5%|▌         | 4/80 [00:15<03:33,  2.81s/it]

[I 2026-08-12 18:36:58,502] Trial 3 finished with value: 0.6211997235500577 and parameters: {'n_estimators': 261, 'learning_rate': 0.10887574000770396, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.8792921435770051, 'colsample_bytree': 0.7747700013286529, 'gamma': 4.470382560470304, 'reg_alpha': 0.4599433003155157, 'reg_lambda': 0.046985453529476216}. Best is trial 1 with value: 0.6659658720592361.

Best trial: 4. Best value: 0.666022:   6%|▋         | 5/80 [00:17<03:00,  2.40s/it]

[I 2026-08-12 18:37:00,172] Trial 4 finished with value: 0.6660216487042812 and parameters: {'n_estimators': 702, 'learning_rate': 0.08568640724238107, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.7352970830566917, 'colsample_bytree': 0.6839857245842766, 'gamma': 1.7721653056888935, 'reg_alpha': 2.7836842188058115e-05, 'reg_lambda': 0.10743506400794994}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:   8%|▊         | 6/80 [00:17<02:10,  1.76s/it]

[I 2026-08-12 18:37:00,693] Trial 5 finished with value: 0.6288928626598347 and parameters: {'n_estimators': 202, 'learning_rate': 0.10953618631337014, 'max_depth': 9, 'min_child_weight': 8, 'subsample': 0.7816375148160878, 'colsample_bytree': 0.6339037872368064, 'gamma': 4.199095571060606, 'reg_alpha': 0.02622457749123312, 'reg_lambda': 0.2792916491237181}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:   9%|▉         | 7/80 [00:19<01:58,  1.62s/it]

[I 2026-08-12 18:37:02,013] Trial 6 finished with value: 0.6599306637622738 and parameters: {'n_estimators': 484, 'learning_rate': 0.09357238649617088, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.8736859966658935, 'colsample_bytree': 0.6793103314572534, 'gamma': 1.6157450026281839, 'reg_alpha': 0.001498554977588645, 'reg_lambda': 0.006910780151744971}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  10%|█         | 8/80 [00:21<02:11,  1.83s/it]

[I 2026-08-12 18:37:04,284] Trial 7 finished with value: 0.6607659808277828 and parameters: {'n_estimators': 951, 'learning_rate': 0.1709268830642383, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.6461377242737247, 'colsample_bytree': 0.6739259293525355, 'gamma': 1.0150334651041537, 'reg_alpha': 0.000496230747227482, 'reg_lambda': 0.004905971391884092}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  11%|█▏        | 9/80 [00:23<02:16,  1.93s/it]

[I 2026-08-12 18:37:06,441] Trial 8 finished with value: 0.6635978691497084 and parameters: {'n_estimators': 664, 'learning_rate': 0.01683617509625524, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9587994154248263, 'colsample_bytree': 0.6969703263488932, 'gamma': 0.8044608664867281, 'reg_alpha': 1.0804166754005715e-05, 'reg_lambda': 0.00012051661451472643}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  12%|█▎        | 10/80 [00:24<02:00,  1.73s/it]

[I 2026-08-12 18:37:07,718] Trial 9 finished with value: 0.6501854117556475 and parameters: {'n_estimators': 485, 'learning_rate': 0.21370840739503355, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.8309817165843266, 'colsample_bytree': 0.8003951047297632, 'gamma': 2.2875712999057467, 'reg_alpha': 0.006511246541835374, 'reg_lambda': 0.5610092688888073}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  14%|█▍        | 11/80 [00:31<03:35,  3.12s/it]

[I 2026-08-12 18:37:13,997] Trial 10 finished with value: 0.6615416106709077 and parameters: {'n_estimators': 933, 'learning_rate': 0.024834581487608254, 'max_depth': 10, 'min_child_weight': 6, 'subsample': 0.6303797103600917, 'colsample_bytree': 0.9969269923795435, 'gamma': 0.1661706306974855, 'reg_alpha': 1.7750929624930784e-05, 'reg_lambda': 1.3005612489733677e-05}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  15%|█▌        | 12/80 [00:33<03:05,  2.72s/it]

[I 2026-08-12 18:37:15,810] Trial 11 finished with value: 0.6510140688603945 and parameters: {'n_estimators': 790, 'learning_rate': 0.04945460422311964, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.756391248700722, 'colsample_bytree': 0.7420944408117834, 'gamma': 2.74271565537015, 'reg_alpha': 0.00016944539469736705, 'reg_lambda': 9.871313492911009}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  16%|█▋        | 13/80 [00:35<02:48,  2.52s/it]

[I 2026-08-12 18:37:17,848] Trial 12 finished with value: 0.6516763015603649 and parameters: {'n_estimators': 790, 'learning_rate': 0.04089687844694388, 'max_depth': 6, 'min_child_weight': 1, 'subsample': 0.723889247783798, 'colsample_bytree': 0.8640668385449112, 'gamma': 2.7705485401741563, 'reg_alpha': 9.051326402533405e-05, 'reg_lambda': 0.0002968884312952868}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  18%|█▊        | 14/80 [00:37<02:43,  2.48s/it]

[I 2026-08-12 18:37:20,253] Trial 13 finished with value: 0.6616474699891347 and parameters: {'n_estimators': 465, 'learning_rate': 0.03948214900732773, 'max_depth': 7, 'min_child_weight': 3, 'subsample': 0.804458381506614, 'colsample_bytree': 0.8573592457903473, 'gamma': 1.4671943679097772, 'reg_alpha': 9.588138994610627e-05, 'reg_lambda': 4.055591729431979}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  19%|█▉        | 15/80 [00:40<02:49,  2.61s/it]

[I 2026-08-12 18:37:23,146] Trial 14 finished with value: 0.6598039343817147 and parameters: {'n_estimators': 779, 'learning_rate': 0.06266062403280298, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.6957478933451755, 'colsample_bytree': 0.719008837022562, 'gamma': 0.35779501696439286, 'reg_alpha': 0.0009867702787943928, 'reg_lambda': 0.0005154425138324464}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  20%|██        | 16/80 [00:42<02:32,  2.39s/it]

[I 2026-08-12 18:37:25,022] Trial 15 finished with value: 0.6332372580840236 and parameters: {'n_estimators': 379, 'learning_rate': 0.01040610878058762, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.84010941672172, 'colsample_bytree': 0.6214732583527645, 'gamma': 2.1801762941191547, 'reg_alpha': 0.04862646240741909, 'reg_lambda': 0.028787729013696306}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 4. Best value: 0.666022:  21%|██▏       | 17/80 [00:43<02:16,  2.17s/it]

[I 2026-08-12 18:37:26,687] Trial 16 finished with value: 0.6415059501378992 and parameters: {'n_estimators': 575, 'learning_rate': 0.15121515130320604, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7465599467660324, 'colsample_bytree': 0.8214058963994993, 'gamma': 3.5685742621274956, 'reg_alpha': 4.2976476902395426e-05, 'reg_lambda': 1.2643350360405259}. Best is trial 4 with value: 0.6660216487042812.

Best trial: 17. Best value: 0.672438:  22%|██▎       | 18/80 [00:46<02:26,  2.36s/it]

[I 2026-08-12 18:37:29,510] Trial 17 finished with value: 0.6724376452966687 and parameters: {'n_estimators': 701, 'learning_rate': 0.027917008274037765, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.6600228768514276, 'colsample_bytree': 0.9691999186077844, 'gamma': 1.07491318637075, 'reg_alpha': 0.00037268893155181283, 'reg_lambda': 1.1138313856783252e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  24%|██▍       | 19/80 [00:48<02:14,  2.20s/it]

[I 2026-08-12 18:37:31,337] Trial 18 finished with value: 0.6534229931877897 and parameters: {'n_estimators': 719, 'learning_rate': 0.2999308166579058, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.6665180933423874, 'colsample_bytree': 0.9829656065793495, 'gamma': 0.8154811241941567, 'reg_alpha': 0.0033738857629154635, 'reg_lambda': 1.151686655523102e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  25%|██▌       | 20/80 [00:50<02:14,  2.25s/it]

[I 2026-08-12 18:37:33,684] Trial 19 finished with value: 0.627447405290975 and parameters: {'n_estimators': 882, 'learning_rate': 0.026206048594597374, 'max_depth': 8, 'min_child_weight': 2, 'subsample': 0.6025604194976532, 'colsample_bytree': 0.9362765719092296, 'gamma': 4.937408834699313, 'reg_alpha': 4.109026947801767e-05, 'reg_lambda': 5.984020924816287e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  26%|██▋       | 21/80 [00:53<02:21,  2.41s/it]

[I 2026-08-12 18:37:36,463] Trial 20 finished with value: 0.6541048413035904 and parameters: {'n_estimators': 849, 'learning_rate': 0.010889324610009488, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.6798079852210268, 'colsample_bytree': 0.9270603637164155, 'gamma': 2.209306689889485, 'reg_alpha': 0.00026256257106374315, 'reg_lambda': 0.0019311513565463151}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  28%|██▊       | 22/80 [00:55<02:13,  2.30s/it]

[I 2026-08-12 18:37:38,521] Trial 21 finished with value: 0.6716356569423615 and parameters: {'n_estimators': 560, 'learning_rate': 0.028768333848567605, 'max_depth': 6, 'min_child_weight': 4, 'subsample': 0.7766494368112203, 'colsample_bytree': 0.7297376728860225, 'gamma': 1.2124808009366908, 'reg_alpha': 0.00045441349826915475, 'reg_lambda': 0.0007676710529230734}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  29%|██▉       | 23/80 [00:58<02:11,  2.30s/it]

[I 2026-08-12 18:37:40,812] Trial 22 finished with value: 0.669788039088939 and parameters: {'n_estimators': 720, 'learning_rate': 0.026546964589023374, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.75497618999814, 'colsample_bytree': 0.657977339089717, 'gamma': 1.0232573181997482, 'reg_alpha': 0.0009678045313343481, 'reg_lambda': 9.45975854461874e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  30%|███       | 24/80 [00:59<02:02,  2.18s/it]

[I 2026-08-12 18:37:42,714] Trial 23 finished with value: 0.669833666997423 and parameters: {'n_estimators': 533, 'learning_rate': 0.027136708753329176, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.7840217893862488, 'colsample_bytree': 0.9147547441298235, 'gamma': 1.0468399387324294, 'reg_alpha': 0.03121934555109108, 'reg_lambda': 4.62933801238587e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  31%|███▏      | 25/80 [01:02<01:58,  2.16s/it]

[I 2026-08-12 18:37:44,832] Trial 24 finished with value: 0.6664353670522178 and parameters: {'n_estimators': 416, 'learning_rate': 0.017716573050215425, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.9956463024460592, 'colsample_bytree': 0.9357336407977286, 'gamma': 0.6119209057118016, 'reg_alpha': 0.27316640673515663, 'reg_lambda': 3.27281922005033e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  32%|███▎      | 26/80 [01:03<01:51,  2.07s/it]

[I 2026-08-12 18:37:46,700] Trial 25 finished with value: 0.6589930100892093 and parameters: {'n_estimators': 550, 'learning_rate': 0.017216041791154837, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.7806377706216538, 'colsample_bytree': 0.893675036037429, 'gamma': 1.2430788365960637, 'reg_alpha': 0.05095944928228104, 'reg_lambda': 0.00022955164518527607}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  34%|███▍      | 27/80 [01:05<01:36,  1.83s/it]

[I 2026-08-12 18:37:47,947] Trial 26 finished with value: 0.6608020332456448 and parameters: {'n_estimators': 357, 'learning_rate': 0.03265201831513569, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.8704440724830447, 'colsample_bytree': 0.9682896471196966, 'gamma': 0.02910528983604932, 'reg_alpha': 0.3914138529505791, 'reg_lambda': 4.0874505959752e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  35%|███▌      | 28/80 [01:07<01:44,  2.01s/it]

[I 2026-08-12 18:37:50,382] Trial 27 finished with value: 0.6703505879332284 and parameters: {'n_estimators': 518, 'learning_rate': 0.022451207063043082, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.7963513550697268, 'colsample_bytree': 0.8909288757454474, 'gamma': 0.4837969379630316, 'reg_alpha': 0.015381751156043861, 'reg_lambda': 1.8117829264836934e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  36%|███▋      | 29/80 [01:10<01:53,  2.22s/it]

[I 2026-08-12 18:37:53,113] Trial 28 finished with value: 0.6716660254309146 and parameters: {'n_estimators': 640, 'learning_rate': 0.02025979887734009, 'max_depth': 5, 'min_child_weight': 7, 'subsample': 0.9114848687996511, 'colsample_bytree': 0.9589841861250319, 'gamma': 0.48658077949090406, 'reg_alpha': 0.01300807625899003, 'reg_lambda': 1.9432498840472574e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  38%|███▊      | 30/80 [01:12<01:52,  2.25s/it]

[I 2026-08-12 18:37:55,417] Trial 29 finished with value: 0.6540193737467499 and parameters: {'n_estimators': 605, 'learning_rate': 0.012929364832270971, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.9184336420533491, 'colsample_bytree': 0.9604538747851442, 'gamma': 1.8416495903345065, 'reg_alpha': 0.0044116349397669615, 'reg_lambda': 0.0016079216292093931}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  39%|███▉      | 31/80 [01:15<02:02,  2.50s/it]

[I 2026-08-12 18:37:58,489] Trial 30 finished with value: 0.6639445332129376 and parameters: {'n_estimators': 642, 'learning_rate': 0.03513331013597439, 'max_depth': 8, 'min_child_weight': 7, 'subsample': 0.7052095047525727, 'colsample_bytree': 0.8510898207627191, 'gamma': 0.5117020606436264, 'reg_alpha': 0.1411215441875817, 'reg_lambda': 0.014824011950867837}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  40%|████      | 32/80 [01:18<01:58,  2.47s/it]

[I 2026-08-12 18:38:00,904] Trial 31 finished with value: 0.6711947705638504 and parameters: {'n_estimators': 528, 'learning_rate': 0.020622643901314623, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.9142392455729655, 'colsample_bytree': 0.885240141008235, 'gamma': 0.3506499430658946, 'reg_alpha': 0.006777241113195766, 'reg_lambda': 1.8834372023047638e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  41%|████▏     | 33/80 [01:20<01:52,  2.40s/it]

[I 2026-08-12 18:38:03,148] Trial 32 finished with value: 0.6602845243514133 and parameters: {'n_estimators': 618, 'learning_rate': 0.020038693835745927, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.9304178781518071, 'colsample_bytree': 0.9546500202125218, 'gamma': 1.311502517614083, 'reg_alpha': 0.00919039841715115, 'reg_lambda': 0.00015412175647974114}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  42%|████▎     | 34/80 [01:22<01:50,  2.41s/it]

[I 2026-08-12 18:38:05,564] Trial 33 finished with value: 0.6627130553479226 and parameters: {'n_estimators': 436, 'learning_rate': 0.01372671708978165, 'max_depth': 6, 'min_child_weight': 7, 'subsample': 0.9460268733441038, 'colsample_bytree': 0.9995054506100691, 'gamma': 0.2350209535506162, 'reg_alpha': 0.0022908030635863065, 'reg_lambda': 2.401888989985914e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  44%|████▍     | 35/80 [01:24<01:42,  2.28s/it]

[I 2026-08-12 18:38:07,559] Trial 34 finished with value: 0.6652280469796465 and parameters: {'n_estimators': 685, 'learning_rate': 0.04992062096922997, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.8933770273542054, 'colsample_bytree': 0.8945324705613814, 'gamma': 0.7325442226898845, 'reg_alpha': 1.7227292956159463, 'reg_lambda': 0.0005938313831316276}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  45%|████▌     | 36/80 [01:27<01:39,  2.25s/it]

[I 2026-08-12 18:38:09,737] Trial 35 finished with value: 0.6628845730510254 and parameters: {'n_estimators': 751, 'learning_rate': 0.03147137580788165, 'max_depth': 6, 'min_child_weight': 5, 'subsample': 0.9827979022784092, 'colsample_bytree': 0.7458947672191406, 'gamma': 1.261855128177949, 'reg_alpha': 0.0005463086255243929, 'reg_lambda': 6.188233530716677e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  46%|████▋     | 37/80 [01:29<01:40,  2.34s/it]

[I 2026-08-12 18:38:12,297] Trial 36 finished with value: 0.6690591239677839 and parameters: {'n_estimators': 592, 'learning_rate': 0.014135789059780038, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.8573066943306321, 'colsample_bytree': 0.8250393235354916, 'gamma': 0.06437118956682636, 'reg_alpha': 0.010408745421322828, 'reg_lambda': 1.0206443241225028e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  48%|████▊     | 38/80 [01:31<01:36,  2.29s/it]

[I 2026-08-12 18:38:14,468] Trial 37 finished with value: 0.6552916511333648 and parameters: {'n_estimators': 647, 'learning_rate': 0.019595536860045788, 'max_depth': 7, 'min_child_weight': 9, 'subsample': 0.9026183448394363, 'colsample_bytree': 0.6022758593197165, 'gamma': 1.8869183300564067, 'reg_alpha': 0.11688655004405141, 'reg_lambda': 2.447978356136928e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  49%|████▉     | 39/80 [01:32<01:18,  1.91s/it]

[I 2026-08-12 18:38:15,489] Trial 38 finished with value: 0.6677452023259146 and parameters: {'n_estimators': 315, 'learning_rate': 0.05256730054574521, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9618121115102725, 'colsample_bytree': 0.9124233586090422, 'gamma': 0.9346261706757819, 'reg_alpha': 0.0017803923213647603, 'reg_lambda': 0.0015409370983287113}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  50%|█████     | 40/80 [01:34<01:13,  1.84s/it]

[I 2026-08-12 18:38:17,170] Trial 39 finished with value: 0.6580659422816602 and parameters: {'n_estimators': 562, 'learning_rate': 0.0222865308906725, 'max_depth': 3, 'min_child_weight': 7, 'subsample': 0.604970790728804, 'colsample_bytree': 0.9505606745044983, 'gamma': 1.6066519027936876, 'reg_alpha': 0.0002824200174727812, 'reg_lambda': 9.994661892650218e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  51%|█████▏    | 41/80 [01:37<01:26,  2.21s/it]

[I 2026-08-12 18:38:20,230] Trial 40 finished with value: 0.6701859957652475 and parameters: {'n_estimators': 681, 'learning_rate': 0.030372490824112686, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8565274039785358, 'colsample_bytree': 0.9763902036760854, 'gamma': 0.45803485583770764, 'reg_alpha': 0.018209786104499817, 'reg_lambda': 0.0003149274940995541}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  52%|█████▎    | 42/80 [01:39<01:23,  2.21s/it]

[I 2026-08-12 18:38:22,438] Trial 41 finished with value: 0.6717287876817959 and parameters: {'n_estimators': 509, 'learning_rate': 0.02216920067969128, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.8178560990320737, 'colsample_bytree': 0.8972217872554397, 'gamma': 0.5795605470844958, 'reg_alpha': 0.013037442858621559, 'reg_lambda': 2.0324913696858673e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  54%|█████▍    | 43/80 [01:42<01:26,  2.34s/it]

[I 2026-08-12 18:38:25,077] Trial 42 finished with value: 0.6664001686055024 and parameters: {'n_estimators': 500, 'learning_rate': 0.015574837093422113, 'max_depth': 6, 'min_child_weight': 6, 'subsample': 0.8931600338936926, 'colsample_bytree': 0.8784649757941145, 'gamma': 0.63408244877136, 'reg_alpha': 0.004026123790318733, 'reg_lambda': 2.4330063365668577e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  55%|█████▌    | 44/80 [01:44<01:19,  2.21s/it]

[I 2026-08-12 18:38:26,997] Trial 43 finished with value: 0.6657803413596333 and parameters: {'n_estimators': 456, 'learning_rate': 0.02199476170224249, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.8301523407365811, 'colsample_bytree': 0.7628154598765525, 'gamma': 1.1967401826027413, 'reg_alpha': 0.006270352082363981, 'reg_lambda': 6.385872332489794e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  56%|█████▋    | 45/80 [01:46<01:16,  2.19s/it]

[I 2026-08-12 18:38:29,140] Trial 44 finished with value: 0.6697863737300866 and parameters: {'n_estimators': 618, 'learning_rate': 0.04035415525259594, 'max_depth': 4, 'min_child_weight': 7, 'subsample': 0.8132221265484376, 'colsample_bytree': 0.8340261501434364, 'gamma': 0.2474418005438579, 'reg_alpha': 0.000671618906458794, 'reg_lambda': 1.0323595688342345e-05}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  57%|█████▊    | 46/80 [01:48<01:17,  2.28s/it]

[I 2026-08-12 18:38:31,611] Trial 45 finished with value: 0.6621105408427346 and parameters: {'n_estimators': 533, 'learning_rate': 0.018621967492380778, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.9151584400314045, 'colsample_bytree': 0.8000886609033844, 'gamma': 0.7783862826513731, 'reg_alpha': 0.08570198161167192, 'reg_lambda': 0.00019515852817208866}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 17. Best value: 0.672438:  59%|█████▉    | 47/80 [01:50<01:06,  2.00s/it]

[I 2026-08-12 18:38:32,969] Trial 46 finished with value: 0.6578826573977687 and parameters: {'n_estimators': 395, 'learning_rate': 0.036301124435110355, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.723597097807657, 'colsample_bytree': 0.9156374001360396, 'gamma': 1.4772429413954309, 'reg_alpha': 1.0597795375365036, 'reg_lambda': 0.008628908605737425}. Best is trial 17 with value: 0.6724376452966687.

Best trial: 47. Best value: 0.673749:  60%|██████    | 48/80 [01:53<01:16,  2.40s/it]

[I 2026-08-12 18:38:36,310] Trial 47 finished with value: 0.6737491970486527 and parameters: {'n_estimators': 992, 'learning_rate': 0.027592454475231426, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9434275929516065, 'colsample_bytree': 0.9854184457220635, 'gamma': 0.36678002626822825, 'reg_alpha': 0.0001431699873014601, 'reg_lambda': 1.6456178585538352e-05}. Best is trial 47 with value: 0.6737491970486527.

Best trial: 47. Best value: 0.673749:  61%|██████▏   | 49/80 [01:56<01:16,  2.47s/it]

[I 2026-08-12 18:38:38,942] Trial 48 finished with value: 0.663042602816027 and parameters: {'n_estimators': 918, 'learning_rate': 0.02908322023608923, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9711165667647746, 'colsample_bytree': 0.9876552103944134, 'gamma': 0.978167105384234, 'reg_alpha': 0.00012591045348913396, 'reg_lambda': 0.07813000614543725}. Best is trial 47 with value: 0.6737491970486527.

Best trial: 47. Best value: 0.673749:  62%|██████▎   | 50/80 [01:58<01:16,  2.54s/it]

[I 2026-08-12 18:38:41,636] Trial 49 finished with value: 0.6663128207210256 and parameters: {'n_estimators': 895, 'learning_rate': 0.04523989969129974, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.6622710027510472, 'colsample_bytree': 0.947142022858807, 'gamma': 0.756602309231959, 'reg_alpha': 1.0962033414253575e-05, 'reg_lambda': 9.722338584531611e-05}. Best is trial 47 with value: 0.6737491970486527.

Best trial: 47. Best value: 0.673749:  64%|██████▍   | 51/80 [02:01<01:13,  2.55s/it]

[I 2026-08-12 18:38:44,213] Trial 50 finished with value: 0.6612643070214383 and parameters: {'n_estimators': 972, 'learning_rate': 0.06463954383982712, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.9441553410078883, 'colsample_bytree': 0.9700925072613511, 'gamma': 1.4593666804570269, 'reg_alpha': 5.811794614072653e-05, 'reg_lambda': 0.0035077917295619435}. Best is trial 47 with value: 0.6737491970486527.

Best trial: 47. Best value: 0.673749:  65%|██████▌   | 52/80 [02:03<01:07,  2.43s/it]

[I 2026-08-12 18:38:46,352] Trial 51 finished with value: 0.6709771094187048 and parameters: {'n_estimators': 482, 'learning_rate': 0.02223914239146441, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9425972451484106, 'colsample_bytree': 0.7171550194043593, 'gamma': 0.3744010974691579, 'reg_alpha': 0.0001916349531131825, 'reg_lambda': 2.2572433985157622e-05}. Best is trial 47 with value: 0.6737491970486527.

Best trial: 52. Best value: 0.676939:  66%|██████▋   | 53/80 [02:06<01:11,  2.64s/it]

[I 2026-08-12 18:38:49,480] Trial 52 finished with value: 0.676938792048787 and parameters: {'n_estimators': 821, 'learning_rate': 0.02399875488523181, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.8815771203707099, 'colsample_bytree': 0.8756357045125285, 'gamma': 0.2639036761635687, 'reg_alpha': 0.0027387260870012603, 'reg_lambda': 1.6329113651044704e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  68%|██████▊   | 54/80 [02:09<01:12,  2.79s/it]

[I 2026-08-12 18:38:52,619] Trial 53 finished with value: 0.6748042844130218 and parameters: {'n_estimators': 839, 'learning_rate': 0.024163702504474895, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.854804706010708, 'colsample_bytree': 0.7935092493297493, 'gamma': 0.006178439570159899, 'reg_alpha': 0.00037708570099517514, 'reg_lambda': 4.3996205591941566e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  69%|██████▉   | 55/80 [02:13<01:13,  2.96s/it]

[I 2026-08-12 18:38:55,970] Trial 54 finished with value: 0.6731246248080476 and parameters: {'n_estimators': 839, 'learning_rate': 0.02434816006322365, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.8741720776875617, 'colsample_bytree': 0.7887146176301049, 'gamma': 0.07604537896277014, 'reg_alpha': 0.0009297081949126019, 'reg_lambda': 4.405325357014339e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  70%|███████   | 56/80 [02:15<01:07,  2.83s/it]

[I 2026-08-12 18:38:58,491] Trial 55 finished with value: 0.6679808196286595 and parameters: {'n_estimators': 832, 'learning_rate': 0.02475568977055971, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.8439082379172032, 'colsample_bytree': 0.7762585488476194, 'gamma': 0.00132310305453337, 'reg_alpha': 0.0010761854487639053, 'reg_lambda': 4.67032702233891e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  71%|███████▏  | 57/80 [02:19<01:12,  3.14s/it]

[I 2026-08-12 18:39:02,355] Trial 56 finished with value: 0.6741415929108829 and parameters: {'n_estimators': 985, 'learning_rate': 0.01588793248846053, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.878125588542434, 'colsample_bytree': 0.797838617751666, 'gamma': 0.2350866471672669, 'reg_alpha': 0.00033587935317119447, 'reg_lambda': 3.607790653067378e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  72%|███████▎  | 58/80 [02:23<01:12,  3.28s/it]

[I 2026-08-12 18:39:05,983] Trial 57 finished with value: 0.670158171245351 and parameters: {'n_estimators': 997, 'learning_rate': 0.011813229978586758, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.8708683765726746, 'colsample_bytree': 0.797134275504919, 'gamma': 0.17005259045226956, 'reg_alpha': 0.0003210817319636169, 'reg_lambda': 7.616057136867403e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  74%|███████▍  | 59/80 [02:25<01:05,  3.12s/it]

[I 2026-08-12 18:39:08,704] Trial 58 finished with value: 0.6616094088129754 and parameters: {'n_estimators': 829, 'learning_rate': 0.015385152336439455, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.8812478975929886, 'colsample_bytree': 0.7885172137623429, 'gamma': 0.2270335001240179, 'reg_alpha': 7.463621509769002e-05, 'reg_lambda': 3.678172400207805e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  75%|███████▌  | 60/80 [02:29<01:02,  3.12s/it]

[I 2026-08-12 18:39:11,846] Trial 59 finished with value: 0.6670127929119125 and parameters: {'n_estimators': 861, 'learning_rate': 0.0244205986312497, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.8468763938306145, 'colsample_bytree': 0.8145382476524161, 'gamma': 0.02876223103389286, 'reg_alpha': 0.00017489899592310849, 'reg_lambda': 0.00032554265475931015}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  76%|███████▋  | 61/80 [02:32<01:01,  3.21s/it]

[I 2026-08-12 18:39:15,274] Trial 60 finished with value: 0.6723137295337693 and parameters: {'n_estimators': 934, 'learning_rate': 0.034928285156365715, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.8866798439733096, 'colsample_bytree': 0.7612435446344845, 'gamma': 0.3163268334794856, 'reg_alpha': 2.582834027225339e-05, 'reg_lambda': 0.00014121522753811713}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  78%|███████▊  | 62/80 [02:35<00:57,  3.22s/it]

[I 2026-08-12 18:39:18,488] Trial 61 finished with value: 0.6674231412625407 and parameters: {'n_estimators': 944, 'learning_rate': 0.03501134317449383, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.8858236698488406, 'colsample_bytree': 0.7559215335357068, 'gamma': 0.26899363014253863, 'reg_alpha': 1.8003633997695323e-05, 'reg_lambda': 0.0001423135769884382}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  79%|███████▉  | 63/80 [02:38<00:52,  3.11s/it]

[I 2026-08-12 18:39:21,361] Trial 62 finished with value: 0.6674182286082567 and parameters: {'n_estimators': 909, 'learning_rate': 0.02742558060644822, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.8602011890816788, 'colsample_bytree': 0.8396299979570487, 'gamma': 0.33202156150552725, 'reg_alpha': 3.6303380131952765e-05, 'reg_lambda': 1.459107932489999e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  80%|████████  | 64/80 [02:41<00:46,  2.91s/it]

[I 2026-08-12 18:39:23,813] Trial 63 finished with value: 0.6739113819075476 and parameters: {'n_estimators': 974, 'learning_rate': 0.042295405315399305, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9289993136861124, 'colsample_bytree': 0.7613209356365445, 'gamma': 0.6837128136070554, 'reg_alpha': 0.0007290402688940389, 'reg_lambda': 3.522267214110882e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  81%|████████▏ | 65/80 [02:43<00:40,  2.73s/it]

[I 2026-08-12 18:39:26,107] Trial 64 finished with value: 0.6722169716959449 and parameters: {'n_estimators': 807, 'learning_rate': 0.08217128111441696, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9236998432186263, 'colsample_bytree': 0.8123232605993258, 'gamma': 0.5897082473408717, 'reg_alpha': 0.0007010369890916368, 'reg_lambda': 4.1035822989359525e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  82%|████████▎ | 66/80 [02:45<00:35,  2.55s/it]

[I 2026-08-12 18:39:28,239] Trial 65 finished with value: 0.6406933061191253 and parameters: {'n_estimators': 997, 'learning_rate': 0.04562690249750281, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9300704581856549, 'colsample_bytree': 0.8682957641816443, 'gamma': 3.8140903060546214, 'reg_alpha': 0.002338680769444828, 'reg_lambda': 3.4150385381265064e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  84%|████████▍ | 67/80 [02:48<00:35,  2.73s/it]

[I 2026-08-12 18:39:31,378] Trial 66 finished with value: 0.665819180288875 and parameters: {'n_estimators': 963, 'learning_rate': 0.015857793639022268, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.6296823643314609, 'colsample_bytree': 0.7883858365453439, 'gamma': 0.9221783781797046, 'reg_alpha': 0.0011404468178153587, 'reg_lambda': 1.3799066715184409e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  85%|████████▌ | 68/80 [02:50<00:30,  2.51s/it]

[I 2026-08-12 18:39:33,401] Trial 67 finished with value: 0.6757960248727591 and parameters: {'n_estimators': 759, 'learning_rate': 0.05475585633592442, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.8963689965273687, 'colsample_bytree': 0.7334611103936041, 'gamma': 0.669933187783685, 'reg_alpha': 0.000115995671890888, 'reg_lambda': 6.140514428143723e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  86%|████████▋ | 69/80 [02:53<00:30,  2.73s/it]

[I 2026-08-12 18:39:36,643] Trial 68 finished with value: 0.6656092242006784 and parameters: {'n_estimators': 874, 'learning_rate': 0.05563700409350655, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9028633354530278, 'colsample_bytree': 0.7008087317572715, 'gamma': 0.12245411166449915, 'reg_alpha': 0.00013778996586707895, 'reg_lambda': 5.954244091455331e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  88%|████████▊ | 70/80 [02:55<00:24,  2.46s/it]

[I 2026-08-12 18:39:38,462] Trial 69 finished with value: 0.6736426199706896 and parameters: {'n_estimators': 762, 'learning_rate': 0.12497234494115934, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.8735229524699537, 'colsample_bytree': 0.7357377487669345, 'gamma': 0.6906198350108204, 'reg_alpha': 0.00023067552304462599, 'reg_lambda': 3.4541974708007435e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  89%|████████▉ | 71/80 [02:57<00:20,  2.30s/it]

[I 2026-08-12 18:39:40,382] Trial 70 finished with value: 0.6513380963647561 and parameters: {'n_estimators': 753, 'learning_rate': 0.12162589887361532, 'max_depth': 10, 'min_child_weight': 3, 'subsample': 0.8615259549472493, 'colsample_bytree': 0.7265090729921337, 'gamma': 0.6622165811248892, 'reg_alpha': 0.00043015669391580666, 'reg_lambda': 0.00023153385891417052}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  90%|█████████ | 72/80 [02:59<00:18,  2.30s/it]

[I 2026-08-12 18:39:42,697] Trial 71 finished with value: 0.6695961485242989 and parameters: {'n_estimators': 771, 'learning_rate': 0.10057465902260831, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.8692358420804585, 'colsample_bytree': 0.7056037904423992, 'gamma': 0.44523987432921885, 'reg_alpha': 0.00023918733553657284, 'reg_lambda': 3.281175518890515e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  91%|█████████▏| 73/80 [03:01<00:15,  2.18s/it]

[I 2026-08-12 18:39:44,594] Trial 72 finished with value: 0.6722694300794665 and parameters: {'n_estimators': 814, 'learning_rate': 0.21168725171039388, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9036222004509444, 'colsample_bytree': 0.7385274398471434, 'gamma': 0.8545914256685712, 'reg_alpha': 8.17999012671058e-05, 'reg_lambda': 8.278789414092958e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  92%|█████████▎| 74/80 [03:04<00:13,  2.18s/it]

[I 2026-08-12 18:39:46,765] Trial 73 finished with value: 0.6604847633520121 and parameters: {'n_estimators': 732, 'learning_rate': 0.18646381915894217, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.8399608893001879, 'colsample_bytree': 0.7661880364399672, 'gamma': 0.13935414909195198, 'reg_alpha': 0.0007141415484428974, 'reg_lambda': 5.292554298126902e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 52. Best value: 0.676939:  94%|█████████▍| 75/80 [03:06<00:10,  2.16s/it]

[I 2026-08-12 18:39:48,875] Trial 74 finished with value: 0.6649052644653011 and parameters: {'n_estimators': 856, 'learning_rate': 0.27125451296162295, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9311718658595248, 'colsample_bytree': 0.6740157348045469, 'gamma': 0.49095798089988457, 'reg_alpha': 0.0015355809186841215, 'reg_lambda': 2.9837460037962154e-05}. Best is trial 52 with value: 0.676938792048787.

Best trial: 75. Best value: 0.680696:  95%|█████████▌| 76/80 [03:08<00:08,  2.12s/it]

[I 2026-08-12 18:39:50,893] Trial 75 finished with value: 0.6806956164348918 and parameters: {'n_estimators': 793, 'learning_rate': 0.07585889011659572, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.8979146985252445, 'colsample_bytree': 0.7445933533191227, 'gamma': 0.7235077637726208, 'reg_alpha': 0.003036500880302069, 'reg_lambda': 1.587516557021529e-05}. Best is trial 75 with value: 0.6806956164348918.

Best trial: 75. Best value: 0.680696:  96%|█████████▋| 77/80 [03:10<00:06,  2.16s/it]

[I 2026-08-12 18:39:53,146] Trial 76 finished with value: 0.6658334135113987 and parameters: {'n_estimators': 973, 'learning_rate': 0.08962143096979618, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.9556334313414594, 'colsample_bytree': 0.7503515000367867, 'gamma': 1.1209870536832747, 'reg_alpha': 0.00272563487203453, 'reg_lambda': 1.8102366502000078e-05}. Best is trial 75 with value: 0.6806956164348918.

Best trial: 75. Best value: 0.680696:  98%|█████████▊| 78/80 [03:12<00:04,  2.14s/it]

[I 2026-08-12 18:39:55,239] Trial 77 finished with value: 0.6759212132981836 and parameters: {'n_estimators': 796, 'learning_rate': 0.07098819730324202, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.8950952504395456, 'colsample_bytree': 0.7386380902300775, 'gamma': 0.7096885399663366, 'reg_alpha': 0.0001076736921307891, 'reg_lambda': 0.00010965803993620885}. Best is trial 75 with value: 0.6806956164348918.

Best trial: 75. Best value: 0.680696:  99%|█████████▉| 79/80 [03:14<00:02,  2.03s/it]

[I 2026-08-12 18:39:57,026] Trial 78 finished with value: 0.6419713196754359 and parameters: {'n_estimators': 805, 'learning_rate': 0.07703890356834285, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.8935563934985282, 'colsample_bytree': 0.6542781749629463, 'gamma': 3.050272447648871, 'reg_alpha': 0.00011237110218439693, 'reg_lambda': 0.00043695369951381245}. Best is trial 75 with value: 0.6806956164348918.

Best trial: 75. Best value: 0.680696: 100%|██████████| 80/80 [03:16<00:00,  2.46s/it]

[I 2026-08-12 18:39:59,218] Trial 79 finished with value: 0.672796270311067 and parameters: {'n_estimators': 790, 'learning_rate': 0.07068134123965893, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.8977444855268406, 'colsample_bytree': 0.7712968186746428, 'gamma': 0.8403886626783426, 'reg_alpha': 6.830765379471864e-05, 'reg_lambda': 1.5015796640673268e-05}. Best is trial 75 with value: 0.6806956164348918.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

In [21]:
study.best_params

{'n_estimators': 793,
 'learning_rate': 0.07585889011659572,
 'max_depth': 4,
 'min_child_weight': 2,
 'subsample': 0.8979146985252445,
 'colsample_bytree': 0.7445933533191227,
 'gamma': 0.7235077637726208,
 'reg_alpha': 0.003036500880302069,
 'reg_lambda': 1.587516557021529e-05}

In [22]:
study.best_value

0.6806956164348918

In [23]:
import json 

save_result_path = Path("artifacts")

save_result_path.mkdir(parents=True, exist_ok=True)

result = {
    "model_name": "XGBoost",
    "best_trial": study.best_trial.number,
    "best_params": study.best_params,
    "best_value": float(study.best_value)
}

with open(save_result_path / "xgboost.json", "w") as f:
    json.dump(result, f, indent=4)