In [1]:
import os 
from pathlib import Path 
import pandas as pd 
import numpy as np

In [2]:
os.chdir("..")

In [3]:
print(os.getcwd())

e:\project_archive\student-dropout-enrolled-graduate-rate-prediction

In [9]:
# Load data

data_path = Path("data/processed")
if not data_path.exists():
    raise FileNotFoundError

X_train = pd.read_csv(data_path / "x_train.csv", sep=';')
y_train = np.load(data_path / "y_train.npy")

X_test = pd.read_csv(data_path / "x_test.csv", sep=';')
y_test = np.load(data_path / "y_test.npy")

In [7]:
X_train.head()

,Marital status,Application mode,Application order,Course,Previous qualification,Previous qualification (grade),Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Inflation rate
0,4,7,1,9147,3,130.0,19,1,5,5,...,0,1,0,0,35,5,5,0,0.000000,0.6
1,1,39,1,9085,1,130.0,37,37,6,6,...,0,1,0,1,25,6,13,3,11.666667,0.6
2,1,1,6,9070,6,119.0,1,1,9,9,...,0,1,1,0,22,6,6,6,14.166667,1.4
3,2,39,1,9238,19,133.1,37,37,9,4,...,0,1,1,0,42,6,0,0,0.000000,2.8
4,1,1,3,9500,1,142.0,37,38,9,9,...,0,1,0,1,22,7,7,6,13.900000,2.6

In [8]:
y_train

array([0, 1, 2, ..., 2, 2, 0], shape=(3539,))

In [10]:
X_test.head()

,Marital status,Application mode,Application order,Course,Previous qualification,Previous qualification (grade),Mother's qualification,Father's qualification,Mother's occupation,Father's occupation,...,Debtor,Tuition fees up to date,Gender,Scholarship holder,Age at enrollment,Curricular units 1st sem (enrolled),Curricular units 1st sem (evaluations),Curricular units 1st sem (approved),Curricular units 1st sem (grade),Inflation rate
0,4,39,1,9130,1,133.1,3,1,5,5,...,0,1,0,1,30,6,7,0,0.000000,0.6
1,1,17,1,9238,1,125.0,4,3,1,1,...,0,1,0,0,18,6,9,5,11.571429,0.3
2,1,17,1,9853,1,133.0,38,38,9,9,...,1,1,0,1,18,7,7,7,12.714286,0.3
3,1,17,2,9670,1,110.0,1,1,4,10,...,0,1,1,0,19,6,8,6,13.857143,2.8
4,1,39,1,9500,1,130.0,37,19,9,8,...,0,1,0,0,27,7,14,0,0.000000,0.6

In [11]:
config = {
    "xgboost": {
        "n_estimators": (200, 1000),
        "learning_rate": (0.01, 0.3),
        "max_depth": (3, 10),
        "min_child_weight": (1, 10),
        "subsample": (0.6, 1.0),
        "colsample_bytree": (0.6, 1.0),
        "gamma": (0.0, 5.0),
        "reg_alpha": (1e-5, 10.0),
        "reg_lambda": (1e-5, 10.0),
    }
}

In [12]:
from xgboost import XGBClassifier


def suggest_params(trial, config):

    cfg = config["xgboost"]

    params = {
        "n_estimators": trial.suggest_int(
            "n_estimators",
            cfg["n_estimators"][0],
            cfg["n_estimators"][1],
        ),

        "learning_rate": trial.suggest_float(
            "learning_rate",
            cfg["learning_rate"][0],
            cfg["learning_rate"][1],
            log=True,
        ),

        "max_depth": trial.suggest_int(
            "max_depth",
            cfg["max_depth"][0],
            cfg["max_depth"][1],
        ),

        "min_child_weight": trial.suggest_int(
            "min_child_weight",
            cfg["min_child_weight"][0],
            cfg["min_child_weight"][1],
        ),

        "subsample": trial.suggest_float(
            "subsample",
            cfg["subsample"][0],
            cfg["subsample"][1],
        ),

        "colsample_bytree": trial.suggest_float(
            "colsample_bytree",
            cfg["colsample_bytree"][0],
            cfg["colsample_bytree"][1],
        ),

        "gamma": trial.suggest_float(
            "gamma",
            cfg["gamma"][0],
            cfg["gamma"][1],
        ),

        "reg_alpha": trial.suggest_float(
            "reg_alpha",
            cfg["reg_alpha"][0],
            cfg["reg_alpha"][1],
            log=True,
        ),

        "reg_lambda": trial.suggest_float(
            "reg_lambda",
            cfg["reg_lambda"][0],
            cfg["reg_lambda"][1],
            log=True,
        ),
    }

    return params

In [13]:
import wandb
from xgboost import XGBClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score


def objective(trial, X, y, config):

    params = suggest_params(
        trial=trial,
        config=config,
    )

    model = XGBClassifier(
        **params,
        objective="multi:softprob",
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1,
    )

    cv = StratifiedKFold(
        n_splits=5,
        shuffle=True,
        random_state=42,
    )

    scores = cross_val_score(
        estimator=model,
        X=X,
        y=y,
        cv=cv,
        scoring="f1_macro",
        n_jobs=-1,
        error_score="raise",
    )

    mean_score = scores.mean()
    std_score = scores.std()

    trial.set_user_attr("cv_std", std_score)

    wandb.log({
        "trial": trial.number,
        "cv_f1_macro": mean_score,
        "cv_f1_macro_std": std_score,
    })

    return mean_score

In [14]:
import pandas as pd
import optuna
import wandb

from xgboost import XGBClassifier
from sklearn.metrics import (
    accuracy_score,
    balanced_accuracy_score,
    precision_score,
    recall_score,
    f1_score,
)

with wandb.init(
    project="student-drop-enroll-grad-preds",
    name="XGBoost-Optuna-v1",
    group="XGBoost",
    tags=["Optuna", "Hyperparameter-Tuning"],
    config={
        "model": "XGBoost",
        "cv": "StratifiedKFold",
        "metric": "f1_macro",
        "n_trials": 80,
        "random_state": 42,
    },
):

    study = optuna.create_study(
        direction="maximize",
        study_name="xgboost_tuning",
    )

    study.optimize(
        lambda trial: objective(
            trial,
            X_train,
            y_train,
            config,
        ),
        n_trials=80,
        show_progress_bar=True,
    )

    best_params = study.best_params

    final_model = XGBClassifier(
        **best_params,
        objective="multi:softprob",
        eval_metric="mlogloss",
        random_state=42,
        n_jobs=-1,
    )

    final_model.fit(X_train, y_train)

    predictions = final_model.predict(X_test)

    metrics = {
        "test_accuracy": accuracy_score(y_test, predictions),
        "test_balanced_accuracy": balanced_accuracy_score(y_test, predictions),
        "test_precision_macro": precision_score(
            y_test,
            predictions,
            average="macro",
            zero_division=0,
        ),
        "test_recall_macro": recall_score(
            y_test,
            predictions,
            average="macro",
            zero_division=0,
        ),
        "test_f1_macro": f1_score(
            y_test,
            predictions,
            average="macro",
        ),
        "test_f1_weighted": f1_score(
            y_test,
            predictions,
            average="weighted",
        ),
    }

    wandb.log(metrics)

    wandb.summary["best_cv_f1_macro"] = study.best_value
    wandb.summary["best_trial"] = study.best_trial.number
    wandb.summary["best_params"] = best_params

    for key, value in metrics.items():
        wandb.summary[key] = value

    results = pd.DataFrame(
        {
            "Actual": y_test,
            "Prediction": predictions,
        }
    )

    wandb.log(
        {
            "Predictions": wandb.Table(dataframe=results)
        }
    )

e:\project_archive\student-dropout-enrolled-graduate-rate-prediction\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
wandb: Currently logged in as: h41497254 (h41497254-none) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

[I 2026-07-31 23:24:54,612] A new study created in memory with name: xgboost_tuning
Best trial: 0. Best value: 0.635352:   1%|▏         | 1/80 [00:09<12:25,  9.44s/it]

[I 2026-07-31 23:25:04,045] Trial 0 finished with value: 0.6353520729326216 and parameters: {'n_estimators': 573, 'learning_rate': 0.024872428728885707, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9847780290316084, 'colsample_bytree': 0.89869255858502, 'gamma': 4.26052667934015, 'reg_alpha': 0.02032054811509089, 'reg_lambda': 1.1347651669678895}. Best is trial 0 with value: 0.6353520729326216.

Best trial: 1. Best value: 0.649583:   2%|▎         | 2/80 [00:15<10:00,  7.69s/it]

[I 2026-07-31 23:25:10,520] Trial 1 finished with value: 0.6495834979319832 and parameters: {'n_estimators': 519, 'learning_rate': 0.025673379408092972, 'max_depth': 7, 'min_child_weight': 2, 'subsample': 0.6906493481629568, 'colsample_bytree': 0.8187175899554845, 'gamma': 2.664824461228968, 'reg_alpha': 0.007296426046583347, 'reg_lambda': 0.3450733251120722}. Best is trial 1 with value: 0.6495834979319832.

Best trial: 1. Best value: 0.649583:   4%|▍         | 3/80 [00:17<06:15,  4.87s/it]

[I 2026-07-31 23:25:12,034] Trial 2 finished with value: 0.6441528174171813 and parameters: {'n_estimators': 584, 'learning_rate': 0.09991754153381252, 'max_depth': 4, 'min_child_weight': 10, 'subsample': 0.7203691310123298, 'colsample_bytree': 0.8493365603731281, 'gamma': 3.656594386849052, 'reg_alpha': 0.00026897308219323853, 'reg_lambda': 0.0005883116573592041}. Best is trial 1 with value: 0.6495834979319832.

Best trial: 1. Best value: 0.649583:   5%|▌         | 4/80 [00:18<04:26,  3.51s/it]

[I 2026-07-31 23:25:13,462] Trial 3 finished with value: 0.6482826040262994 and parameters: {'n_estimators': 500, 'learning_rate': 0.2959448997246983, 'max_depth': 7, 'min_child_weight': 5, 'subsample': 0.84062280152798, 'colsample_bytree': 0.7173856556118504, 'gamma': 2.72210964906817, 'reg_alpha': 0.011469862246334202, 'reg_lambda': 4.6935158185342845}. Best is trial 1 with value: 0.6495834979319832.

Best trial: 1. Best value: 0.649583:   6%|▋         | 5/80 [00:20<03:26,  2.76s/it]

[I 2026-07-31 23:25:14,880] Trial 4 finished with value: 0.631070652474269 and parameters: {'n_estimators': 560, 'learning_rate': 0.07844081249070674, 'max_depth': 8, 'min_child_weight': 4, 'subsample': 0.9967686935432789, 'colsample_bytree': 0.797282241722507, 'gamma': 3.557553139492145, 'reg_alpha': 0.0003734826964901292, 'reg_lambda': 1.0535098658417536e-05}. Best is trial 1 with value: 0.6495834979319832.

Best trial: 1. Best value: 0.649583:   8%|▊         | 6/80 [00:21<02:44,  2.22s/it]

[I 2026-07-31 23:25:16,072] Trial 5 finished with value: 0.6020189943559248 and parameters: {'n_estimators': 326, 'learning_rate': 0.011067939918395442, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.9966221060709998, 'colsample_bytree': 0.8667765518946662, 'gamma': 4.106049453431503, 'reg_alpha': 0.2729465615980557, 'reg_lambda': 1.1328448275835679}. Best is trial 1 with value: 0.6495834979319832.

Best trial: 6. Best value: 0.652988:   9%|▉         | 7/80 [00:23<02:29,  2.05s/it]

[I 2026-07-31 23:25:17,776] Trial 6 finished with value: 0.6529877837912614 and parameters: {'n_estimators': 722, 'learning_rate': 0.11677390006259437, 'max_depth': 9, 'min_child_weight': 1, 'subsample': 0.8641475385308273, 'colsample_bytree': 0.7854464074309553, 'gamma': 2.474231438814431, 'reg_alpha': 0.0008725483592006952, 'reg_lambda': 4.7394882774967915}. Best is trial 6 with value: 0.6529877837912614.

Best trial: 6. Best value: 0.652988:  10%|█         | 8/80 [00:25<02:23,  2.00s/it]

[I 2026-07-31 23:25:19,653] Trial 7 finished with value: 0.6506221473564516 and parameters: {'n_estimators': 685, 'learning_rate': 0.2331750515671972, 'max_depth': 3, 'min_child_weight': 9, 'subsample': 0.6015602646806424, 'colsample_bytree': 0.8634591694472267, 'gamma': 3.769455213628881, 'reg_alpha': 0.24219496831627982, 'reg_lambda': 0.0012871044300301158}. Best is trial 6 with value: 0.6529877837912614.

Best trial: 8. Best value: 0.670223:  11%|█▏        | 9/80 [00:29<03:06,  2.62s/it]

[I 2026-07-31 23:25:23,648] Trial 8 finished with value: 0.6702232691011256 and parameters: {'n_estimators': 792, 'learning_rate': 0.05787398996414705, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.7545942342584573, 'colsample_bytree': 0.8169387521342042, 'gamma': 0.02002904774323966, 'reg_alpha': 0.005504454316712614, 'reg_lambda': 0.0031006260068589322}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  12%|█▎        | 10/80 [00:30<02:39,  2.28s/it]

[I 2026-07-31 23:25:25,160] Trial 9 finished with value: 0.6208849831205618 and parameters: {'n_estimators': 227, 'learning_rate': 0.017488854723336906, 'max_depth': 5, 'min_child_weight': 10, 'subsample': 0.8230303511662401, 'colsample_bytree': 0.860737577701136, 'gamma': 4.821474151295871, 'reg_alpha': 0.1369322374079445, 'reg_lambda': 0.01294422383182025}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  14%|█▍        | 11/80 [00:37<04:20,  3.78s/it]

[I 2026-07-31 23:25:32,352] Trial 10 finished with value: 0.6598957383599097 and parameters: {'n_estimators': 966, 'learning_rate': 0.04804699722414733, 'max_depth': 10, 'min_child_weight': 7, 'subsample': 0.7571806973963672, 'colsample_bytree': 0.9969856792060174, 'gamma': 0.24281211319997514, 'reg_alpha': 1.0270661820599736e-05, 'reg_lambda': 1.0593735649717451e-05}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  15%|█▌        | 12/80 [00:44<05:21,  4.73s/it]

[I 2026-07-31 23:25:39,257] Trial 11 finished with value: 0.661709755787973 and parameters: {'n_estimators': 957, 'learning_rate': 0.05089823082278396, 'max_depth': 10, 'min_child_weight': 7, 'subsample': 0.751093838592959, 'colsample_bytree': 0.9774618278351556, 'gamma': 0.01722227782008242, 'reg_alpha': 1.200129769233786e-05, 'reg_lambda': 1.2070489528921886e-05}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  16%|█▋        | 13/80 [00:49<05:10,  4.64s/it]

[I 2026-07-31 23:25:43,676] Trial 12 finished with value: 0.6568745298771446 and parameters: {'n_estimators': 986, 'learning_rate': 0.04695499466317203, 'max_depth': 6, 'min_child_weight': 7, 'subsample': 0.7730893147642798, 'colsample_bytree': 0.6272992604255991, 'gamma': 0.02837985264644583, 'reg_alpha': 6.528368817102678, 'reg_lambda': 0.0001820512010807974}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  18%|█▊        | 14/80 [00:52<04:42,  4.28s/it]

[I 2026-07-31 23:25:47,119] Trial 13 finished with value: 0.6686311969576282 and parameters: {'n_estimators': 856, 'learning_rate': 0.04905303380219946, 'max_depth': 10, 'min_child_weight': 7, 'subsample': 0.6410686256630088, 'colsample_bytree': 0.9925114278198456, 'gamma': 0.9078625732050626, 'reg_alpha': 0.00012187224426515965, 'reg_lambda': 0.015160203658147207}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  19%|█▉        | 15/80 [00:54<03:57,  3.66s/it]

[I 2026-07-31 23:25:49,336] Trial 14 finished with value: 0.6611403121309747 and parameters: {'n_estimators': 828, 'learning_rate': 0.16754843204706746, 'max_depth': 8, 'min_child_weight': 5, 'subsample': 0.6320874223564784, 'colsample_bytree': 0.9409860805315031, 'gamma': 1.1384089823405323, 'reg_alpha': 8.646181834890967e-05, 'reg_lambda': 0.030206346459159993}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  20%|██        | 16/80 [00:57<03:34,  3.34s/it]

[I 2026-07-31 23:25:51,958] Trial 15 finished with value: 0.668852693304483 and parameters: {'n_estimators': 834, 'learning_rate': 0.06880309895900019, 'max_depth': 6, 'min_child_weight': 8, 'subsample': 0.6756182603019929, 'colsample_bytree': 0.7213009174467899, 'gamma': 1.1043834600130544, 'reg_alpha': 0.0021257381228544318, 'reg_lambda': 0.01996623141735989}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  21%|██▏       | 17/80 [00:59<03:08,  2.99s/it]

[I 2026-07-31 23:25:54,127] Trial 16 finished with value: 0.6693157321940616 and parameters: {'n_estimators': 810, 'learning_rate': 0.07260388439105159, 'max_depth': 5, 'min_child_weight': 8, 'subsample': 0.6883782537981756, 'colsample_bytree': 0.737291512722808, 'gamma': 1.3047824871432145, 'reg_alpha': 0.0019523093670372781, 'reg_lambda': 0.0031313683324436055}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  22%|██▎       | 18/80 [01:01<02:49,  2.73s/it]

[I 2026-07-31 23:25:56,237] Trial 17 finished with value: 0.6606680722009945 and parameters: {'n_estimators': 722, 'learning_rate': 0.031729079207456275, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.802752633761266, 'colsample_bytree': 0.7145079281443172, 'gamma': 1.8066420786563562, 'reg_alpha': 0.00297308893552506, 'reg_lambda': 0.0022420220866540544}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 8. Best value: 0.670223:  24%|██▍       | 19/80 [01:03<02:34,  2.54s/it]

[I 2026-07-31 23:25:58,348] Trial 18 finished with value: 0.6698585470813486 and parameters: {'n_estimators': 769, 'learning_rate': 0.13816625275738983, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8915025895632464, 'colsample_bytree': 0.6393307767209256, 'gamma': 0.6618929872528121, 'reg_alpha': 0.06035306329172562, 'reg_lambda': 0.00021351226655093493}. Best is trial 8 with value: 0.6702232691011256.

Best trial: 19. Best value: 0.677588:  25%|██▌       | 20/80 [01:05<02:15,  2.26s/it]

[I 2026-07-31 23:25:59,951] Trial 19 finished with value: 0.6775877477917189 and parameters: {'n_estimators': 696, 'learning_rate': 0.16157597011642857, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.9384557142483714, 'colsample_bytree': 0.6003312273069528, 'gamma': 0.6892216422740459, 'reg_alpha': 0.042248903230999314, 'reg_lambda': 0.00010645435450077591}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  26%|██▋       | 21/80 [01:06<01:51,  1.89s/it]

[I 2026-07-31 23:26:00,978] Trial 20 finished with value: 0.6433517366616902 and parameters: {'n_estimators': 421, 'learning_rate': 0.18970617955698602, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.9247664336744903, 'colsample_bytree': 0.6123458972964073, 'gamma': 1.79452582776503, 'reg_alpha': 2.163574593863868, 'reg_lambda': 9.864750982969117e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  28%|██▊       | 22/80 [01:08<02:01,  2.10s/it]

[I 2026-07-31 23:26:03,572] Trial 21 finished with value: 0.6757817801892588 and parameters: {'n_estimators': 693, 'learning_rate': 0.13159910236634645, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8969184038679395, 'colsample_bytree': 0.6560747997371849, 'gamma': 0.484343245418589, 'reg_alpha': 0.07413101643494407, 'reg_lambda': 0.00010061839019380738}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  29%|██▉       | 23/80 [01:10<01:54,  2.02s/it]

[I 2026-07-31 23:26:05,394] Trial 22 finished with value: 0.6681655005644045 and parameters: {'n_estimators': 630, 'learning_rate': 0.09773847329116139, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9367980763438997, 'colsample_bytree': 0.6638470780573897, 'gamma': 0.6863240699722095, 'reg_alpha': 0.8932448469837235, 'reg_lambda': 4.932967688050572e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  30%|███       | 24/80 [01:12<01:49,  1.96s/it]

[I 2026-07-31 23:26:07,216] Trial 23 finished with value: 0.6717751900079695 and parameters: {'n_estimators': 660, 'learning_rate': 0.14981387620672856, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.9485026221340606, 'colsample_bytree': 0.6693727382800245, 'gamma': 0.48365571738353624, 'reg_alpha': 0.04521571590122471, 'reg_lambda': 4.775484873034996e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  31%|███▏      | 25/80 [01:14<01:45,  1.92s/it]

[I 2026-07-31 23:26:09,042] Trial 24 finished with value: 0.6540813302927696 and parameters: {'n_estimators': 641, 'learning_rate': 0.15177287682077856, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.9487236471803319, 'colsample_bytree': 0.6789388955150296, 'gamma': 1.6435115213899167, 'reg_alpha': 0.035621581393763396, 'reg_lambda': 5.6141724888864046e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  32%|███▎      | 26/80 [01:17<01:56,  2.15s/it]

[I 2026-07-31 23:26:11,747] Trial 25 finished with value: 0.6643421649615024 and parameters: {'n_estimators': 890, 'learning_rate': 0.21450484779573686, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.8955805048494225, 'colsample_bytree': 0.6753861357065478, 'gamma': 0.5100449830672618, 'reg_alpha': 0.09081953122269716, 'reg_lambda': 0.00035160286687279475}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  34%|███▍      | 27/80 [01:18<01:47,  2.03s/it]

[I 2026-07-31 23:26:13,471] Trial 26 finished with value: 0.6533015498495213 and parameters: {'n_estimators': 653, 'learning_rate': 0.29567217220899056, 'max_depth': 3, 'min_child_weight': 1, 'subsample': 0.9571725221162649, 'colsample_bytree': 0.6455891747362811, 'gamma': 1.4108343130162946, 'reg_alpha': 0.3014589164694656, 'reg_lambda': 3.580227925744253e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  35%|███▌      | 28/80 [01:20<01:34,  1.83s/it]

[I 2026-07-31 23:26:14,834] Trial 27 finished with value: 0.666257470434821 and parameters: {'n_estimators': 442, 'learning_rate': 0.1209510529865372, 'max_depth': 6, 'min_child_weight': 2, 'subsample': 0.8969630915439262, 'colsample_bytree': 0.6035947784841874, 'gamma': 0.5011578682134987, 'reg_alpha': 0.024497683819462244, 'reg_lambda': 0.0005484692189669794}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  36%|███▋      | 29/80 [01:21<01:31,  1.78s/it]

[I 2026-07-31 23:26:16,521] Trial 28 finished with value: 0.6481031014679891 and parameters: {'n_estimators': 728, 'learning_rate': 0.09606300773221955, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.8581580504998116, 'colsample_bytree': 0.6890379836790875, 'gamma': 2.077558547392093, 'reg_alpha': 0.7667316505351255, 'reg_lambda': 2.8537762651756117e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  38%|███▊      | 30/80 [01:23<01:27,  1.74s/it]

[I 2026-07-31 23:26:18,157] Trial 29 finished with value: 0.6606197811140726 and parameters: {'n_estimators': 585, 'learning_rate': 0.2210928680625327, 'max_depth': 4, 'min_child_weight': 1, 'subsample': 0.9712370609431983, 'colsample_bytree': 0.7659871410704266, 'gamma': 0.8820233029547724, 'reg_alpha': 0.023960795794563047, 'reg_lambda': 0.00012893925803118578}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  39%|███▉      | 31/80 [01:25<01:32,  1.88s/it]

[I 2026-07-31 23:26:20,368] Trial 30 finished with value: 0.6695348403492509 and parameters: {'n_estimators': 898, 'learning_rate': 0.15501776008981882, 'max_depth': 3, 'min_child_weight': 2, 'subsample': 0.913925054683765, 'colsample_bytree': 0.6490284828548334, 'gamma': 0.3744976585707579, 'reg_alpha': 0.05581208316236046, 'reg_lambda': 0.0009374859520547641}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  40%|████      | 32/80 [01:28<01:38,  2.05s/it]

[I 2026-07-31 23:26:22,805] Trial 31 finished with value: 0.672960693285451 and parameters: {'n_estimators': 773, 'learning_rate': 0.03513402133027309, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.9647362840103527, 'colsample_bytree': 0.9128198462035888, 'gamma': 0.037216650944994725, 'reg_alpha': 0.0070786550251580906, 'reg_lambda': 9.73171623383359e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  41%|████▏     | 33/80 [01:30<01:40,  2.13s/it]

[I 2026-07-31 23:26:25,135] Trial 32 finished with value: 0.665383004687005 and parameters: {'n_estimators': 752, 'learning_rate': 0.028738342398236895, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.9678917220282377, 'colsample_bytree': 0.9195304059389146, 'gamma': 0.819759042840309, 'reg_alpha': 0.010432650189450809, 'reg_lambda': 7.51111431518203e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  42%|████▎     | 34/80 [01:33<01:48,  2.36s/it]

[I 2026-07-31 23:26:28,017] Trial 33 finished with value: 0.6710868073192188 and parameters: {'n_estimators': 665, 'learning_rate': 0.019033686788952404, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9228856284398743, 'colsample_bytree': 0.6193168450005961, 'gamma': 0.35365410441159595, 'reg_alpha': 0.015853660050173066, 'reg_lambda': 2.8207857034104637e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  44%|████▍     | 35/80 [01:35<01:47,  2.38s/it]

[I 2026-07-31 23:26:30,451] Trial 34 finished with value: 0.6745963202880598 and parameters: {'n_estimators': 582, 'learning_rate': 0.0347978711479295, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.8743429277461253, 'colsample_bytree': 0.7564648744344673, 'gamma': 0.24994077901586165, 'reg_alpha': 0.005227662368453164, 'reg_lambda': 0.0003376963212251557}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  45%|████▌     | 36/80 [01:37<01:34,  2.16s/it]

[I 2026-07-31 23:26:32,085] Trial 35 finished with value: 0.6670834987485776 and parameters: {'n_estimators': 519, 'learning_rate': 0.037183845364446674, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.8746773047553029, 'colsample_bytree': 0.7523752488595508, 'gamma': 1.0422516950404304, 'reg_alpha': 0.004845052801351537, 'reg_lambda': 0.0003231490752493681}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  46%|████▋     | 37/80 [01:39<01:34,  2.21s/it]

[I 2026-07-31 23:26:34,408] Trial 36 finished with value: 0.6740985987198601 and parameters: {'n_estimators': 583, 'learning_rate': 0.020755043772384563, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.8347707208273676, 'colsample_bytree': 0.8987791140021978, 'gamma': 0.23169425651947373, 'reg_alpha': 0.0007209385662772247, 'reg_lambda': 0.0008592487484397266}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  48%|████▊     | 38/80 [01:42<01:36,  2.29s/it]

[I 2026-07-31 23:26:36,881] Trial 37 finished with value: 0.6555540394868109 and parameters: {'n_estimators': 488, 'learning_rate': 0.010914350386576692, 'max_depth': 6, 'min_child_weight': 6, 'subsample': 0.824925303806956, 'colsample_bytree': 0.6936405896384359, 'gamma': 1.5231720130812976, 'reg_alpha': 0.0004340474628223038, 'reg_lambda': 0.006261768892802083}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  49%|████▉     | 39/80 [01:43<01:26,  2.11s/it]

[I 2026-07-31 23:26:38,591] Trial 38 finished with value: 0.6370908057909922 and parameters: {'n_estimators': 585, 'learning_rate': 0.01746963268743595, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.8433132647665993, 'colsample_bytree': 0.8260378273581822, 'gamma': 3.1187777116652007, 'reg_alpha': 0.0008296154669085737, 'reg_lambda': 0.09335182512670219}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  50%|█████     | 40/80 [01:47<01:39,  2.48s/it]

[I 2026-07-31 23:26:41,929] Trial 39 finished with value: 0.666275554461887 and parameters: {'n_estimators': 568, 'learning_rate': 0.02470342154582299, 'max_depth': 7, 'min_child_weight': 6, 'subsample': 0.7902105793825721, 'colsample_bytree': 0.7868818807000693, 'gamma': 0.26643969383372557, 'reg_alpha': 0.0008331732907625932, 'reg_lambda': 0.001312685958698156}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  51%|█████▏    | 41/80 [01:50<01:44,  2.69s/it]

[I 2026-07-31 23:26:45,095] Trial 40 finished with value: 0.6675737484827798 and parameters: {'n_estimators': 612, 'learning_rate': 0.012698440618057442, 'max_depth': 5, 'min_child_weight': 6, 'subsample': 0.8795619239045753, 'colsample_bytree': 0.8895899264333006, 'gamma': 0.6951308702898518, 'reg_alpha': 6.269162106027256e-05, 'reg_lambda': 0.0006030885519164688}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  52%|█████▎    | 42/80 [01:53<01:42,  2.70s/it]

[I 2026-07-31 23:26:47,839] Trial 41 finished with value: 0.6734710055045946 and parameters: {'n_estimators': 701, 'learning_rate': 0.022704731271821633, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.979182617901676, 'colsample_bytree': 0.9476982500533816, 'gamma': 0.190761625047832, 'reg_alpha': 0.009322408906230328, 'reg_lambda': 0.0002280931050916258}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  54%|█████▍    | 43/80 [01:56<01:42,  2.77s/it]

[I 2026-07-31 23:26:50,771] Trial 42 finished with value: 0.6670629062674935 and parameters: {'n_estimators': 700, 'learning_rate': 0.014487487116377038, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.987487507018093, 'colsample_bytree': 0.9560221711656743, 'gamma': 0.2656450645020778, 'reg_alpha': 0.012941521935173938, 'reg_lambda': 0.0002626116094924653}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  55%|█████▌    | 44/80 [01:58<01:35,  2.64s/it]

[I 2026-07-31 23:26:53,119] Trial 43 finished with value: 0.6682845156040325 and parameters: {'n_estimators': 550, 'learning_rate': 0.021739981730284262, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.9092471978521828, 'colsample_bytree': 0.8849293980876157, 'gamma': 0.6681119635971677, 'reg_alpha': 0.1372989257022451, 'reg_lambda': 0.0005550635064485158}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  56%|█████▋    | 45/80 [02:01<01:35,  2.72s/it]

[I 2026-07-31 23:26:56,001] Trial 44 finished with value: 0.6745466653392278 and parameters: {'n_estimators': 694, 'learning_rate': 0.021760806073784333, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.8452765864026385, 'colsample_bytree': 0.9508401042835755, 'gamma': 0.19494073191276579, 'reg_alpha': 0.004034685157519379, 'reg_lambda': 0.0012872780871510173}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  57%|█████▊    | 46/80 [02:04<01:32,  2.71s/it]

[I 2026-07-31 23:26:58,686] Trial 45 finished with value: 0.6668197981885344 and parameters: {'n_estimators': 612, 'learning_rate': 0.01504375906485226, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8520251788968894, 'colsample_bytree': 0.9792110528992726, 'gamma': 1.1766091547485105, 'reg_alpha': 0.0038535599062450494, 'reg_lambda': 0.005606835195203659}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  59%|█████▉    | 47/80 [02:05<01:20,  2.44s/it]

[I 2026-07-31 23:27:00,518] Trial 46 finished with value: 0.6687639449529164 and parameters: {'n_estimators': 483, 'learning_rate': 0.027270028493100954, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.8289468758622954, 'colsample_bytree': 0.84832218252451, 'gamma': 0.5540430450747831, 'reg_alpha': 0.0013053756695448142, 'reg_lambda': 0.0010282868788080287}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  60%|██████    | 48/80 [02:07<01:07,  2.10s/it]

[I 2026-07-31 23:27:01,814] Trial 47 finished with value: 0.6745157867041118 and parameters: {'n_estimators': 384, 'learning_rate': 0.08287480512493556, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.8693401215258624, 'colsample_bytree': 0.9250170765633818, 'gamma': 0.8701306741901382, 'reg_alpha': 0.00018121901336838787, 'reg_lambda': 1.8970684774169985e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  61%|██████▏   | 49/80 [02:08<00:55,  1.78s/it]

[I 2026-07-31 23:27:02,860] Trial 48 finished with value: 0.6706242259261018 and parameters: {'n_estimators': 354, 'learning_rate': 0.12648302514568543, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.8754458762653952, 'colsample_bytree': 0.8317744417694549, 'gamma': 0.8395421736434356, 'reg_alpha': 3.909145474604751e-05, 'reg_lambda': 1.943472003705284e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  62%|██████▎   | 50/80 [02:08<00:43,  1.46s/it]

[I 2026-07-31 23:27:03,564] Trial 49 finished with value: 0.661218223854012 and parameters: {'n_estimators': 204, 'learning_rate': 0.08156323075317212, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.8632097784425552, 'colsample_bytree': 0.8032931684233717, 'gamma': 1.2939570762552446, 'reg_alpha': 0.0002775157056258841, 'reg_lambda': 1.6855323311334756e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  64%|██████▍   | 51/80 [02:09<00:36,  1.25s/it]

[I 2026-07-31 23:27:04,331] Trial 50 finished with value: 0.623838496105859 and parameters: {'n_estimators': 287, 'learning_rate': 0.060694005713404386, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.7993647804059085, 'colsample_bytree': 0.9739320928817581, 'gamma': 4.701529536573981, 'reg_alpha': 0.42703070455217523, 'reg_lambda': 0.00012923430023691935}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  65%|██████▌   | 52/80 [02:11<00:38,  1.37s/it]

[I 2026-07-31 23:27:05,992] Trial 51 finished with value: 0.661890789962867 and parameters: {'n_estimators': 435, 'learning_rate': 0.10684205525884051, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.841449057484915, 'colsample_bytree': 0.926094864588907, 'gamma': 0.15175428453067494, 'reg_alpha': 0.0001877168615665894, 'reg_lambda': 0.002238222649909602}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  66%|██████▋   | 53/80 [02:13<00:42,  1.58s/it]

[I 2026-07-31 23:27:08,039] Trial 52 finished with value: 0.6716913188722395 and parameters: {'n_estimators': 387, 'learning_rate': 0.03737801711767795, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.8115689678488498, 'colsample_bytree': 0.9324876791305514, 'gamma': 0.4173250197081696, 'reg_alpha': 0.0005169444710783287, 'reg_lambda': 0.0001584804985988596}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  68%|██████▊   | 54/80 [02:14<00:37,  1.43s/it]

[I 2026-07-31 23:27:09,133] Trial 53 finished with value: 0.6535203891313484 and parameters: {'n_estimators': 306, 'learning_rate': 0.0409809693330626, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.7808966415521904, 'colsample_bytree': 0.9017346851091271, 'gamma': 1.0105056335579825, 'reg_alpha': 2.495568838897866e-05, 'reg_lambda': 9.743060282492657}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  69%|██████▉   | 55/80 [02:16<00:36,  1.46s/it]

[I 2026-07-31 23:27:10,646] Trial 54 finished with value: 0.6682793244289079 and parameters: {'n_estimators': 527, 'learning_rate': 0.17838518395165737, 'max_depth': 4, 'min_child_weight': 6, 'subsample': 0.8875659628741932, 'colsample_bytree': 0.9663444771925149, 'gamma': 0.7891792787627032, 'reg_alpha': 0.0020313041038242737, 'reg_lambda': 0.7963359193402096}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  70%|███████   | 56/80 [02:16<00:31,  1.30s/it]

[I 2026-07-31 23:27:11,582] Trial 55 finished with value: 0.6658812859093974 and parameters: {'n_estimators': 259, 'learning_rate': 0.2637302818303729, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.9323633283428551, 'colsample_bytree': 0.708321498977454, 'gamma': 0.13247499095590026, 'reg_alpha': 0.13484020557021278, 'reg_lambda': 0.005531155927352328}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  71%|███████▏  | 57/80 [02:20<00:48,  2.09s/it]

[I 2026-07-31 23:27:15,516] Trial 56 finished with value: 0.6558349386546692 and parameters: {'n_estimators': 744, 'learning_rate': 0.08587479003722535, 'max_depth': 6, 'min_child_weight': 3, 'subsample': 0.9064107198375548, 'colsample_bytree': 0.9027856789925235, 'gamma': 0.004975992661633233, 'reg_alpha': 0.00016817456080086884, 'reg_lambda': 0.0015935067045457461}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  72%|███████▎  | 58/80 [02:24<00:57,  2.60s/it]

[I 2026-07-31 23:27:19,311] Trial 57 finished with value: 0.6696630952495336 and parameters: {'n_estimators': 670, 'learning_rate': 0.01981914124048801, 'max_depth': 9, 'min_child_weight': 7, 'subsample': 0.8158556700026725, 'colsample_bytree': 0.8759532116391635, 'gamma': 0.5421284914516566, 'reg_alpha': 0.0028951691940375364, 'reg_lambda': 0.0004833069494817017}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  74%|███████▍  | 59/80 [02:26<00:52,  2.50s/it]

[I 2026-07-31 23:27:21,584] Trial 58 finished with value: 0.6605964453084554 and parameters: {'n_estimators': 791, 'learning_rate': 0.1974773498149486, 'max_depth': 3, 'min_child_weight': 5, 'subsample': 0.7262697027601609, 'colsample_bytree': 0.6304653521034222, 'gamma': 0.9331500533717996, 'reg_alpha': 0.001246136450445827, 'reg_lambda': 6.992281391866387e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  75%|███████▌  | 60/80 [02:29<00:50,  2.51s/it]

[I 2026-07-31 23:27:24,120] Trial 59 finished with value: 0.6683252570278851 and parameters: {'n_estimators': 692, 'learning_rate': 0.06451848807205751, 'max_depth': 5, 'min_child_weight': 3, 'subsample': 0.8530421520044046, 'colsample_bytree': 0.8481599202817739, 'gamma': 0.28569015658541774, 'reg_alpha': 0.000552315305870552, 'reg_lambda': 0.0007755174628246517}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  76%|███████▋  | 61/80 [02:31<00:42,  2.25s/it]

[I 2026-07-31 23:27:25,753] Trial 60 finished with value: 0.6675989724488384 and parameters: {'n_estimators': 469, 'learning_rate': 0.03069223422236557, 'max_depth': 4, 'min_child_weight': 8, 'subsample': 0.8329626885105867, 'colsample_bytree': 0.6040581593715459, 'gamma': 0.6798172951653962, 'reg_alpha': 0.032362565680342056, 'reg_lambda': 0.0032274598366137885}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  78%|███████▊  | 62/80 [02:33<00:43,  2.43s/it]

[I 2026-07-31 23:27:28,606] Trial 61 finished with value: 0.6764362274861591 and parameters: {'n_estimators': 709, 'learning_rate': 0.022577762802071983, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.9843582800336509, 'colsample_bytree': 0.9452457048224183, 'gamma': 0.2438851597061544, 'reg_alpha': 0.00798946376579217, 'reg_lambda': 0.00023139969634049034}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  79%|███████▉  | 63/80 [02:36<00:40,  2.36s/it]

[I 2026-07-31 23:27:30,816] Trial 62 finished with value: 0.6590503437396675 and parameters: {'n_estimators': 717, 'learning_rate': 0.01583533627770764, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.940920608725169, 'colsample_bytree': 0.9414919017159611, 'gamma': 0.4281297738419634, 'reg_alpha': 0.01857393070619138, 'reg_lambda': 0.00028728418118719736}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  80%|████████  | 64/80 [02:38<00:36,  2.27s/it]

[I 2026-07-31 23:27:32,866] Trial 63 finished with value: 0.6550225107063163 and parameters: {'n_estimators': 615, 'learning_rate': 0.02454182202801385, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.9981459891718611, 'colsample_bytree': 0.9569388923845438, 'gamma': 1.2059207360357507, 'reg_alpha': 0.0071519557772004114, 'reg_lambda': 0.0003943386774279067}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  81%|████████▏ | 65/80 [02:40<00:36,  2.41s/it]

[I 2026-07-31 23:27:35,603] Trial 64 finished with value: 0.6702067962622875 and parameters: {'n_estimators': 861, 'learning_rate': 0.043605388612780106, 'max_depth': 5, 'min_child_weight': 5, 'subsample': 0.8708661008547455, 'colsample_bytree': 0.6549658031165868, 'gamma': 0.5890573061609072, 'reg_alpha': 0.07571685661697959, 'reg_lambda': 1.0260359072921418e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  82%|████████▎ | 66/80 [02:43<00:32,  2.34s/it]

[I 2026-07-31 23:27:37,793] Trial 65 finished with value: 0.6646724898455448 and parameters: {'n_estimators': 681, 'learning_rate': 0.021988508095126303, 'max_depth': 3, 'min_child_weight': 3, 'subsample': 0.9211584729025362, 'colsample_bytree': 0.9989043630251201, 'gamma': 0.3179040147628029, 'reg_alpha': 0.0033766943046475597, 'reg_lambda': 3.8360731492354114e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  84%|████████▍ | 67/80 [02:45<00:31,  2.45s/it]

[I 2026-07-31 23:27:40,505] Trial 66 finished with value: 0.6733750785447511 and parameters: {'n_estimators': 641, 'learning_rate': 0.05149908265508228, 'max_depth': 4, 'min_child_weight': 2, 'subsample': 0.9083738551104391, 'colsample_bytree': 0.7331792615437032, 'gamma': 0.17293684749575067, 'reg_alpha': 0.0012379694419225194, 'reg_lambda': 0.0001651116170390962}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  85%|████████▌ | 68/80 [02:48<00:31,  2.59s/it]

[I 2026-07-31 23:27:43,408] Trial 67 finished with value: 0.6696370329917098 and parameters: {'n_estimators': 761, 'learning_rate': 0.013338072039622492, 'max_depth': 4, 'min_child_weight': 4, 'subsample': 0.88668685632983, 'colsample_bytree': 0.912152919281793, 'gamma': 0.3988354948581363, 'reg_alpha': 0.00486877986645263, 'reg_lambda': 0.0001020998760114097}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  86%|████████▋ | 69/80 [02:50<00:26,  2.38s/it]

[I 2026-07-31 23:27:45,312] Trial 68 finished with value: 0.6514127675617211 and parameters: {'n_estimators': 541, 'learning_rate': 0.01763653915942404, 'max_depth': 3, 'min_child_weight': 6, 'subsample': 0.9539049272880068, 'colsample_bytree': 0.9821670408688197, 'gamma': 0.9621755947075277, 'reg_alpha': 0.035159796323409896, 'reg_lambda': 1.814919472713767e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  88%|████████▊ | 70/80 [02:52<00:23,  2.35s/it]

[I 2026-07-31 23:27:47,575] Trial 69 finished with value: 0.6766317411344124 and parameters: {'n_estimators': 820, 'learning_rate': 0.13399626224649827, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.8978060918428153, 'colsample_bytree': 0.7656117051952216, 'gamma': 0.6847577681492498, 'reg_alpha': 7.984669401143715e-05, 'reg_lambda': 0.0018273681703731561}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  89%|████████▉ | 71/80 [02:54<00:20,  2.24s/it]

[I 2026-07-31 23:27:49,561] Trial 70 finished with value: 0.6718683041867652 and parameters: {'n_estimators': 814, 'learning_rate': 0.13718086325050735, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.8983606213849555, 'colsample_bytree': 0.6305665689796595, 'gamma': 0.7819683666529919, 'reg_alpha': 2.3079415177220437e-05, 'reg_lambda': 0.00938670796609808}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  90%|█████████ | 72/80 [02:58<00:21,  2.69s/it]

[I 2026-07-31 23:27:53,293] Trial 71 finished with value: 0.6570339678324661 and parameters: {'n_estimators': 917, 'learning_rate': 0.16744695927467865, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.8604125399946825, 'colsample_bytree': 0.756777702002133, 'gamma': 0.005201392027363139, 'reg_alpha': 5.743737370969146e-05, 'reg_lambda': 0.0024519615275056584}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  91%|█████████▏| 73/80 [03:00<00:17,  2.53s/it]

[I 2026-07-31 23:27:55,462] Trial 72 finished with value: 0.6726287200456925 and parameters: {'n_estimators': 734, 'learning_rate': 0.10197102945187385, 'max_depth': 5, 'min_child_weight': 9, 'subsample': 0.8442740010439113, 'colsample_bytree': 0.9572768811285866, 'gamma': 0.5484663053525689, 'reg_alpha': 0.0002723508182041835, 'reg_lambda': 0.0007592190547974092}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  92%|█████████▎| 74/80 [03:03<00:15,  2.62s/it]

[I 2026-07-31 23:27:58,289] Trial 73 finished with value: 0.6661902331738014 and parameters: {'n_estimators': 848, 'learning_rate': 0.09031512598505409, 'max_depth': 4, 'min_child_weight': 3, 'subsample': 0.9326929544803185, 'colsample_bytree': 0.9321108840226426, 'gamma': 0.1750946294869094, 'reg_alpha': 8.422151106584408e-05, 'reg_lambda': 6.75431439461011e-05}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  94%|█████████▍| 75/80 [03:05<00:12,  2.43s/it]

[I 2026-07-31 23:28:00,277] Trial 74 finished with value: 0.6649909312162194 and parameters: {'n_estimators': 791, 'learning_rate': 0.10835138268252421, 'max_depth': 4, 'min_child_weight': 9, 'subsample': 0.8837738282625485, 'colsample_bytree': 0.7782624579764614, 'gamma': 1.431878593614798, 'reg_alpha': 0.00012534958898205605, 'reg_lambda': 0.00039007077684105563}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  95%|█████████▌| 76/80 [03:07<00:08,  2.15s/it]

[I 2026-07-31 23:28:01,785] Trial 75 finished with value: 0.6593874233881551 and parameters: {'n_estimators': 603, 'learning_rate': 0.1304155671429897, 'max_depth': 6, 'min_child_weight': 10, 'subsample': 0.8673724686676895, 'colsample_bytree': 0.6958011076835143, 'gamma': 1.0891501381076993, 'reg_alpha': 0.11344817539708574, 'reg_lambda': 0.001355755104088589}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  96%|█████████▋| 77/80 [03:08<00:06,  2.05s/it]

[I 2026-07-31 23:28:03,598] Trial 76 finished with value: 0.6711353542075613 and parameters: {'n_estimators': 712, 'learning_rate': 0.11781113051018478, 'max_depth': 5, 'min_child_weight': 2, 'subsample': 0.9819038551815814, 'colsample_bytree': 0.8060284269653422, 'gamma': 0.7430196764894724, 'reg_alpha': 0.0101935501579454, 'reg_lambda': 0.003482801708670514}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  98%|█████████▊| 78/80 [03:11<00:04,  2.18s/it]

[I 2026-07-31 23:28:06,078] Trial 77 finished with value: 0.6681946035834352 and parameters: {'n_estimators': 936, 'learning_rate': 0.07279048082125254, 'max_depth': 3, 'min_child_weight': 4, 'subsample': 0.896090162843923, 'colsample_bytree': 0.6576497309875056, 'gamma': 0.4468375078875655, 'reg_alpha': 0.21233358277305095, 'reg_lambda': 0.0017158789007252352}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588:  99%|█████████▉| 79/80 [03:13<00:02,  2.23s/it]

[I 2026-07-31 23:28:08,416] Trial 78 finished with value: 0.6714721874451588 and parameters: {'n_estimators': 643, 'learning_rate': 0.02015404383415536, 'max_depth': 4, 'min_child_weight': 5, 'subsample': 0.9229246547907006, 'colsample_bytree': 0.7409722194133906, 'gamma': 0.6265088355860507, 'reg_alpha': 0.02639680936570852, 'reg_lambda': 0.00021130045225038212}. Best is trial 19 with value: 0.6775877477917189.

Best trial: 19. Best value: 0.677588: 100%|██████████| 80/80 [03:15<00:00,  2.44s/it]

[I 2026-07-31 23:28:09,795] Trial 79 finished with value: 0.6630584662708053 and parameters: {'n_estimators': 391, 'learning_rate': 0.15004438379065144, 'max_depth': 5, 'min_child_weight': 4, 'subsample': 0.9449978913062133, 'colsample_bytree': 0.8633723887861656, 'gamma': 0.3012609511120151, 'reg_alpha': 0.016697212305385286, 'reg_lambda': 0.000930228766634587}. Best is trial 19 with value: 0.6775877477917189.

wandb: ERROR The nbformat package was not found. It is required to save notebook history.

In [15]:
study.best_params

{'n_estimators': 696,
 'learning_rate': 0.16157597011642857,
 'max_depth': 3,
 'min_child_weight': 3,
 'subsample': 0.9384557142483714,
 'colsample_bytree': 0.6003312273069528,
 'gamma': 0.6892216422740459,
 'reg_alpha': 0.042248903230999314,
 'reg_lambda': 0.00010645435450077591}

In [16]:
study.best_value

0.6775877477917189

In [17]:
import json 

save_result_path = Path("artifacts/reports")

save_result_path.mkdir(parents=True, exist_ok=True)

result = {
    "model_name": "XGBoost",
    "best_trial": study.best_trial.number,
    "best_params": study.best_params,
    "best_value": float(study.best_value)
}

with open(save_result_path / "xgboost.json", "w") as f:
    json.dump(result, f, indent=4)